### ISSUE TITLE
Where are the binaries for the kiji project?

### ISSUE THREAD

**Issue by abhitechdojo** [kijiproject/kiji#3]
I am reading a book which gave me this URL to use

curl -O http://archive.kiji.org/tarballs/kiji-bento-dashi-1.4.3-release.tar.gz

I installed this and it worked very well. But apparently this is a very old distribution of hadoop.

So can you please give me the path to the latest binary? Something which comes with CDH 5.1.2. The web server does not allow listing of content. so I cannot do

http://archive.kiji.org/tarballs/

Also.... is this the right medium to ask for help from the kiji team? or is there a support forum somewhere.

**Comment by gwu** [comment]
There aren't any binaries hosted with the latest code, so you'd have to build from source. The primary developers from WibiData, the original corporate sponsor for Kiji, have moved on.

Currently, there is only user support through https://groups.google.com/a/kiji.org/forum/#!forum/user until another community group picks up the role of sponsor/owner. I'm discussing this with a few potential companies now, so hopefully it won't be too long.
